language: node_js
# To fix the npm version in 4.x
# refs: https://github.com/travis-ci/travis-ci/issues/4653#issuecomment-194051953
before_install: 'if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi'
matrix:
  include:
    - os: osx
      install:
        - 'if [[ ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} = "master" ]]; then yarn; fi'
      node_js:
        - 'stable'
        - 'lts/*'
      script:
        - 'if [[ ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} = "master" && ${TRAVIS_NODE_VERSION} = "stable" ]]; then
             npm run lint;
             npm run test;
             ./script/e2e-runner.sh;
           fi'
    - os: linux
      node_js:
        - 'stable'
        - 'lts/*'
      script:
        - 'npm run lint'
        - 'npm run test'
        - 'if [[ ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} = "master" &&\
                 ${TRAVIS_NODE_VERSION} = "stable" &&\
                 ${TRAVIS_PULL_REQUEST} != "false" ]]; then ./script/e2e-runner.sh; fi'
