name: asmstnote # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  asmstnote:
    command: desktop-launch $SNAP/etc/boostnote/Boostnote
    plugs:
     - browser-support
     - network
     - unity7
     - gsettings
     # - home
     # - pulseaudio
     # - opengl

parts:
  src:
    plugin: nodejs
    source: .

  deps:
    plugin: nil
    stage-packages:
      - libgconf-2-4
      - libnss3
      - libxss1
      - fontconfig-config

  desktop-integration:
    plugin: nil
    stage-packages:
      - libappindicator1
      - libdbusmenu-glib4
      - libnotify4
      - libunity9

  launcher:
    plugin: dump
    source: .
    stage:
      - etc/boostnote
    organize:
      dist/Boostnote-linux-x64: etc/boostnote
    after: [desktop-glib-only]
